# Generated by Django 3.2 on 2024-01-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20231229_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='thumb',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
