# Generated by Django 3.2 on 2024-01-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='travel_date',
            field=models.CharField(max_length=100),
        ),
    ]
