# Generated by Django 3.2 on 2024-01-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20240111_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='selected_pax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
