# Generated by Django 3.2 on 2024-01-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_booking_selected_pax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='selected_pax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100000, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='travel_date',
            field=models.DateField(),
        ),
    ]
