# Generated by Django 3.2 on 2024-01-11 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_booking_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='category',
        ),
    ]
