# Generated by Django 3.2 on 2024-01-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_remove_booking_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='category_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
