# Generated by Django 3.2 on 2024-01-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_booking_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='home_category',
            field=models.BooleanField(default=False),
        ),
    ]
