# Generated by Django 3.2 on 2024-01-17 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_excursion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcusionBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_people', models.IntegerField()),
                ('travel_date', models.DateField()),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('excursion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.excursion')),
            ],
        ),
    ]
