# Generated by Django 3.2 on 2024-01-19 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0020_excusionbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour_Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=100, null=True)),
                ('selected_pax', models.DecimalField(blank=True, decimal_places=2, max_digits=100000, null=True)),
                ('number_of_people', models.IntegerField()),
                ('travel_date', models.DateField()),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.tour')),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
